hystrix:
  metrics.enabled: false
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 100
      queueSizeRejectionThreshold: 100
  command:
    default.execution.isolation.thread.timeoutInMilliseconds: 1000
    createOrder.execution.isolation.thread.timeoutInMilliseconds: 2000

logging:
  level:
    org.springframework: WARN
    com.ordercommand: INFO